### ISSUE TITLE
Support deep watching

### ISSUE THREAD

**Issue by Queatz** [angular-ui/ui-validate#13] opened 2015-08-27 06:21 UTC
`$watch` has a 3rd parameter, and when set to `true` it watches the entire object.  It would be useful to be able to do i.e. `ui-validate-watch-deep="..."`

**Comment by PowerKiKi** [comment] 2015-08-27 07:32
Isn't it an almost duplicate of #12 ? would #12 be enough for your use-case ?

**Comment by blowsie** [comment] 2015-08-27 11:49
I also believe this is a duplicate of #12

**Comment by Queatz** [comment] 2015-08-27 16:18
`$watchCollection` only goes 1 level deep, which might not work 100% as needed in my case.

**Comment by r0b-** [comment] 2015-09-27 10:23
I made a pull request for that feature (ui-validate-watch-object-equality)... https://github.com/angular-ui/ui-validate/pull/16

**Comment by PowerKiKi** [comment] 2015-10-23 01:58
Closed via #16

**Closed as completed by PowerKiKi** 2015-10-23 01:58 UTC
